DB_USER: sidydiopbalde

DB_PASSWORD: Toubakhayra

dsn: mysql:host=localhost;port=3306;dbname=Mon_Ecole;charset=utf8mb4

Session : Core\Session

Validator : Core\Validator

MysqlDatabaseInterface : Core\Database\MysqlDatabaseInterface 

MysqlDatabase : Core\Database\MysqlDatabase

# Services:
#     Session:
#           class: Core\Session
#     Validator:
#           class: Core\Validator
#     ValidatorInterface :
#         class: Core\ValidatorInterface

Services:
  Core\SessionInterface:
    class: Core\Session
  Core\ValidatorInterface:
    class: Core\Validator